spring:
  datasource:
    url: jdbc:mysql://localhost:3307/booking_system?createDatabaseIfNotExist=true&currentSchema=booking_system
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    schemas: booking_system