spring:
  profiles:
    active: @spring.profiles.active@
  mail:
    host: smtp.gmail.com
    port: 587
    username: examplejava07@gmail.com
    password: hmocuxzqgdcxedvp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    confirmLinkIP : http://localhost:8080/

jwt:
  secret: bookingSystem
  # those are the expiration durations for jwt access and jwt refresh
  # introduced in milliseconds which are equal to 3 minutes and 5 minutes
  accessExpirationMs: 180000
  refreshExpirationMs: 300000

redis:
  # exchange these fields for yours
  host: localhost
  port: 6379
  password: root