spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_system?createDatabaseIfNotExist=true&currentSchema=booking_system
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    schemas: booking_system

jwt:
  secret : bookingSystem
  # For test
  accessExpirationMs : 120000
  refreshExpirationMs : 240000
server:
  port: 8090
