spring:
  datasource:
      url: jdbc:mysql://localhost:3306/booking_system?currentSchema=booking_system
      username: root
      password: root
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
    schemas: booking_system

