spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_system?createDatabaseIfNotExist=true&currentSchema=booking_system
    username: user
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
  #  flyway:
  #   baseline-on-migrate: true
  #  schemas: booking_system

jwt:
  secret: bookingSystem
  # those are the expiration durations for jwt access and jwt refresh
  # introduced in milliseconds which are equal to 3 minutes and 5 minutes
  accessExpirationMs: 180000
  refreshExpirationMs: 300000

redis:
  host: localhost
  port: 6379
  password: 12345

