spring:
  datasource:
   # url: jdbc:mysql://localhost:3306/booking_system? currentSchema=booking_system&allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:mysql://localhost:3306/booking_system?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baselineOnMigrate: true
    schemas: booking_system